

target 'HR_Bluetooth_Example' do
  pod 'HR_Bluetooth', :path => '../'

  target 'HR_Bluetooth_Tests' do
    inherit! :search_paths
    
    pod 'HR_DataHexString'
    pod 'HR_ChainProperty'

  end
end
